---
title: "XML_GHS_Searcher"
format: html
editor: visual
---

```{r, message=FALSE}
library(tidyverse)
library(PubChemR)
```

```{r}
GHS_searcher<-function(result_json_object){
  result<-result_json_object
  for (i in 1:length(result[["result"]][["Hierarchies"]][["Hierarchy"]])){
    if(result[["result"]][["Hierarchies"]][["Hierarchy"]][[i]][["SourceName"]]=="GHS Classification (UNECE)"){
      return(i)
    }
          
  }
}
```

```{r}
hazards_retriever<-function(index,result_json_object){
  result<-result_json_object
  hierarchy<-result[["result"]][["Hierarchies"]][["Hierarchy"]][[index]]
  i<-1
  output_list<-rep(NA,length(hierarchy[["Node"]]))
  while(str_detect(hierarchy[["Node"]][[i]][["Information"]][["Name"]],"H") & i<length(hierarchy[["Node"]])){
    output_list[i]<-hierarchy[["Node"]][[i]][["Information"]][["Name"]]
    i<-i+1
  }
  return(output_list[!is.na(output_list)])
}
```

```{r}

chemical_vec<-c("azoxystrobin","flumioxazin")

result_f<-get_pug_rest(identifier = "Azadirachtin", namespace = "name", domain = "compound",operation="classification", output = "JSON")

hazards_retriever(GHS_searcher(result_f),result_f)


result_d<-get_pug_rest(identifier = "hexythiazox", namespace = "name", domain = "compound",operation="classification", output = "JSON")

hazards_retriever(GHS_searcher(result_d),result_d)

```
